### ISSUE TITLE
google-credentials.md steps do not match the new Google Play Console

### ISSUE THREAD

**Issue by mattmapadmi** [fastlane/docs#1003]
https://github.com/fastlane/docs/blob/master/docs/includes/google-credentials.md

Step 7 says that the "Release Manager" or "Project Lead" role should be granted, however in the new Play console, there is no concept of roles.

I don't know enough about how Supply works internally to raise a PR to update the docs with the required permissions. At a minimum I think the "Release apps to testing tracks" is needed to upload the APK.

**Comment by rogerluan** [comment]
Thanks for bringing this up! This has been resolved here https://github.com/fastlane/docs/pull/1031 😊 Let me know if you have any further questions!
