### ISSUE TITLE
Clarify supported Ruby versions

### ISSUE THREAD

**Issue by tripplilley** [fastlane/docs#1018]
Installation instructions in the docs homepage at https://docs.fastlane.tools/ don't mention min/max Ruby versions. My first install attempt, using my macOS Catalina system default Ruby, didn't work because it was too old. My second attempt, using the Ruby 3.0.0 from `ruby-install --latest ruby`, didn't work because it's too new.

I eventually found the TL;DR in fastlane/fastlane#17931, which mentioned **2.4-2.7** being just right. Having that directly in the install docs would've saved me some frustration 😄

**Comment by ainame** [comment]
This is great! I'll look into it 😄

**Comment by ainame** [comment]
I started updating the installation page on this branch😄 

https://github.com/fastlane/docs/commit/11649fea8777e7d1eb147d3cdedecf8a294ca399
