### ISSUE TITLE
Support fastlane produce with App Store Connect API?

### ISSUE THREAD

**Issue by jheidschwarz** [fastlane/docs#1024]
Last week our build pipelines stopped working because of the 2 factor login restrictions by Apple. So we changed our pipelines to use the new App Store Connect API key json file. Sadly "fastlane produce" is not supported yet. Are there any plans to add this in the near future?

**Comment by rogerluan** [comment]
Please check these:

https://github.com/fastlane/fastlane/discussions/17889
https://github.com/fastlane/fastlane/discussions/18106
