### ISSUE TITLE
Broken link to Google Play Console in docs

### ISSUE THREAD

**Issue by lkesteloot** [fastlane/docs#1036]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The link to the Google Play Console is broken in the docs.

Visit [this page](https://docs.fastlane.tools/actions/supply/), click the link to "Google Play Console" under "Setup". It refreshes the page because the `title` attribute was set instead of the `href` attribute.

![image](https://user-images.githubusercontent.com/419771/110878580-50f3f980-8290-11eb-925d-c224173da2ee.png)

**Comment by rogerluan** [comment]
This seems to be an issue with either mkdocs or how we're "importing" google-credentials.md into another document. The markdown looks right, so no idea what this issue could be caused by, for the time being 😬

**Comment by rogerluan** [comment]
Nevermind! I was looking at an outdated version of the file 😅  I spotted the issue already!
