### ISSUE TITLE
新mac mini MI芯片上fastlane打包问题

### ISSUE THREAD

**Issue by ywx372421496** [fastlane/docs#1047]
Xcode使用Rosetta打开是可以打包的 ，但是fastlane还是不行，一直报IPA processing failed。
我该如何配置fastlane

**Comment by rogerluan** [comment]
Hi @ywx372421496, this repository is just for documentation. To report issues, please create an issue in https://github.com/fastlane/fastlane instead, and in English, please.
Cheers.

**Comment by ywx372421496** [comment]
ok
