### ISSUE TITLE
App Store Connect API documentation missing download_dsyms

### ISSUE THREAD

**Issue by bdrelling** [fastlane/docs#1111]
Documentation for [Using App Store Connect API](https://docs.fastlane.tools/app-store-connect-api/) does not include info on [download_dsyms](https://docs.fastlane.tools/actions/download_dsyms/), which makes the usage misleading.

If `pem` is included as `No/No` under **Supported Actions/Tools**, I would have expected to see `download_dsyms` with the same information. 

I would have opened this as a Pull Request, but I assumed there may be a reason why and wanted to raise as an issue first. I'm also not sure if there are other App Store Connect-related actions that could be included in this list for completion.

Thank you!

**Comment by bdrelling** [comment]
Right, I totally get that. I mean that it should be documented to show
No/No in the same way, because it’s a lane that users _expect_ to interact
with the App Store Connect API.

I would still advocate for its inclusion in that doc page, for full
clarity. I can’t think of a good reason not to document it there.

Thanks!

**Comment by rogerluan** [comment]
Ah gotcha, that's a good point ye. Document at least that it's not supported, and how users can workaround. I see value in that 👍
