### ISSUE TITLE
Service Account User role is not required

### ISSUE THREAD

**Issue by maBarabas** [fastlane/docs#1166]
When [setting up supply](https://docs.fastlane.tools/getting-started/android/setup/#setting-up-supply), in the "Collect your Google credentials" section, the steps tells us to add the "Service Account User" role to the created Service Account.

This role is for impersonating other Service Accounts and is not actually required in this case. From the [docs](https://cloud.google.com/iam/docs/service-accounts#user-role):
>  Users granted the Service Account User role on a service account can use it to indirectly access all the resources to which the service account has access.

The permissions are configured completely from the Google Play Console, and the Service Account can have roles assigned at all in the Google Cloud Console.

I've removed the Service Account User role from the Service Account, and `fastlane supply init --internal` command worked fine.

Could some with more GCP experience confirm if this is correct?

**Comment by rogerluan** [comment]
Very interesting, @maBarabas ! I'll investigate whether this is really the case 🙏  it would be great if we can confirm this and update our docs, because the less permissions/roles/access the account needs, the better!

I'll keep you posted, but this might take some time

**Comment by janbrasna** [comment]
I believe the "Select a role" step was removed in #1218 @ https://github.com/fastlane/docs/pull/1218/commits/3398c30e88e2058f7067cba41a1339e139b05344 (=can be closed now?)

**Comment by rogerluan** [comment]
Nice catch @janbrasna ! 🎯  Thanks!

Closing this issue as resolved :)
