### ISSUE TITLE
Typo in return value for `run_tests` "Output has of results with"

### ISSUE THREAD

**Issue by simonbromberg** [fastlane/docs#1176]
I was looking at https://docs.fastlane.tools/actions/run_tests/ and noticed this confusing line with a typo:

> **Outputs has of results** with :number_of_tests, :number_of_failures, :number_of_retries, :number_of_tests_excluding_retries, :number_of_failures_excluding_retries

<img width="817" alt="image" src="https://user-images.githubusercontent.com/2942298/185822698-b345932e-1298-4305-a639-1a8f0f1c9c47.png">

But I was looking at `/docs/actions/run_tests.md` and I don't see that line anywhere.

Also a bit unclear how you use these return values, maybe partially because of the typo.

**Comment by rogerluan** [comment]
Weird typo indeed! The author probably meant `hash` 😊 You could've found where to edit it by clicking in `Edit on GitHub` at the top of the page, which would lead you here: https://github.com/fastlane/fastlane/blob/259e8dd5f74fd900e031525efc09dcd28db8fe53/fastlane/lib/fastlane/actions/run_tests.rb#L60

**Comment by simonbromberg** [comment]
Thanks. Can you use the output if there is a failure if `run_tests` throws an exception on failure?

**Comment by rogerluan** [comment]
@simonbromberg yes, because there's an option that lets you not fail the lane if the tests fail :)

https://github.com/fastlane/fastlane/blob/ff41f3556f1baf8e700477e50f65be728780aa94/scan/lib/scan/options.rb#L526-L530

**Comment by simonbromberg** [comment]
Right yea, wasn't sure if there was a way to do it without that.
