### ISSUE TITLE
Wrong Setting up supply link in Beta Deployment section

### ISSUE THREAD

**Issue by efstathiosntonas** [fastlane/docs#1185]
This `Setting up supply` link leads to a 404: https://github.com/fastlane/docs/blob/master/docs/getting-started/android/beta-deployment.md#deploy-to-beta-distribution-services-using-fastlane

Correct link should be: http://docs.fastlane.tools/getting-started/android/setup/#setting-up-supply instead of: https://docs.fastlane.tools/getting-started/android/beta-deployment/setup/#setting-up-supply

**Comment by rogerluan** [comment]
@efstathiosntonas this is working as expected, you're not supposed to be browsing them from GitHub, but from http://docs.fastlane.tools instead (this git repo is just the source code for the website, which is generated based on the template files in this repo). 

If you go to http://docs.fastlane.tools/getting-started/android/beta-deployment/ and click the [Setting up supply](http://docs.fastlane.tools/getting-started/android/setup/#setting-up-supply) link there, you'll see you'll be redirected to the correct place 🙏
