### ISSUE TITLE
"if metric.installed?" Error

### ISSUE THREAD

**Issue by christruong90** [fastlane/docs#1201]
Issues submitted here should consist of bugs/features of our [docs site](https://docs.fastlane.tools/).
If you're looking to submit an issue (bug/question/feature) about _fastlane_ itself, please do so in the [main repo](https://github.com/fastlane/fastlane/issues). 

Our machine is calling the "fastlane pilot export -a <app_bundle_id>" but the following error is returned:

undefined method `installed?' for nil:NilClass (NoMethodError)

          if metric.installed?
          
          
![image](https://github.com/fastlane/docs/assets/19395006/e0cfd483-8293-47f7-b286-3a8ac9892b78)

Our fastlane is also updated to the current version, 2.214.0

**Comment by christruong90** [comment]
@joshdholtz

**Comment by Krishsidu** [comment]
I am seeing the issue as well.

**Comment by christruong90** [comment]
posted in wrong section.
