### ISSUE TITLE
How to publish new app to App Store and Play Store from fastlane command?

### ISSUE THREAD

**Issue by lakshydeep-14** [fastlane/docs#1224]
I want to publish new app to Play Store and App Store. How to do?

**Comment by rogerluan** [comment]
@lakshydeep-14 please start at https://docs.fastlane.tools to understand how _fastlane_ works and read the getting started guides 🙏

**Comment by lakshydeep-14** [comment]
I want to create app on playstore and appstore from the fastlane command.
How to do this?

I am not getting any leads.

**Comment by rogerluan** [comment]
To **_create a new app_** using _fastlane_:
- Android: I believe it's http://docs.fastlane.tools/actions/create_app_on_managed_play_store
- iOS: https://docs.fastlane.tools/actions/produce

**Comment by lakshydeep-14** [comment]
Thanks, It worked!
It helped to create apps on appstore and playstore. But now I need to push
the apk/ipa file to the respective stores.
What Should I do?
