### ISSUE TITLE
[Proposal] Plugins page design

### ISSUE THREAD

**Issue by Antondomashnev** [fastlane/docs#149]
I think the [Available Plugins](https://docs.fastlane.tools/plugins/available-plugins/) page could be improved to show the user more information inline, so the user doesn't have to go to the plugin's repo and check the Readme. I personally like the section on [Danger.Systems](http://danger.systems/) with information about plugins.

**Comment by KrauseFx** [comment]
Hey @Antondomashnev, I agree it could be a better list of available plugins. Are you interested in diving into this and helping us improve it? 🚀

**Comment by Antondomashnev** [comment]
@KrauseFx I could try =)

**Comment by janpio** [comment]
Danger.Systems plugin section doesn't seem o exist any more.
