### ISSUE TITLE
'sh' action not documented

### ISSUE THREAD

**Issue by GoodMirek** [fastlane/docs#182]
I am not able to find any documentation regarding the 'sh' action. Neither in https://docs.fastlane.tools/actions nor `fastlane actions`
I am happy to create a description based on the code of the sh_helper.rb, but not sure how to include it in the docs.
Please may you advise?

**Comment by KrauseFx** [comment]
Nice catch, definitely something that should be fixed. Basically you'd have to add a new _fastlane_ action to the _fastlane_ main code base called `sh.rb` with a similar content to [`import.rb`](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/import.rb). 

Let me know if you need any help setting this up 👍 Once this got merged, the `docs` page will be automatically updated on the next _fastlane_ release

**Comment by GoodMirek** [comment]
Thanks for advice, will try.

**Comment by KrauseFx** [comment]
I'll close this issue for now 👍
