### ISSUE TITLE
Missing description of option "workspace" for action "match"

### ISSUE THREAD

**Issue by GoodMirek** [fastlane/docs#183]
Description of option "workspace" for action "match" is missing from https://docs.fastlane.tools/actions/#match

Looking at source code, I struggle to understand whether the option:
1. Specifies where to checkout the git repo, implies git_url parameter is still mandatory.
-OR-
2. Specifies where to read/write provisioning profiles and certs as an alternative to use of git repo, implies being mutually exclusive with git_url parameter.

**Comment by KrauseFx** [comment]
Nice catch, the `workspace` shouldn't be set manually actually, I think that's why the value is nil and it's not described. I'll update the docs generator to exclude values with no description 👍

**Comment by KrauseFx** [comment]
Just pushed https://github.com/fastlane/fastlane/pull/6919
