### ISSUE TITLE
[Proposal] Action parameter types

### ISSUE THREAD

**Issue by zapjonny** [fastlane/docs#196]
In the docs of actions, why don't you define the type of the parameter, or possible parameters if only a few exists? https://docs.fastlane.tools/actions/#building So for the tables Parameters, there should be Key Description Type or similar columns.

I had to look up an example fastfile to see what kind of value was needed for "include_bitcode". (Yes, 1, Maybe, Always, "Yes", "1", true, True, ON, on, On) ...

**Comment by KrauseFx** [comment]
Since Ruby is not strongly typed, there is usually no way to know the allowed types and values. Most parameters are verified on run-time by the `verify_block`. If you know a good way to make this work, let us know 👍

**Comment by joshdholtz** [comment]
I believe this require a decent size change on the main fastlane repo as well. I would recommend creating an issue/proposal over there with this feature since docs for actions are created automatically now 😊
