### ISSUE TITLE
Broken link for license

### ISSUE THREAD

**Issue by elitree** [fastlane/docs#209]
The [bottom of the doc](https://docs.fastlane.tools/#license) mentions the license.  The link address in the blurb currently points to:

https://docs.fastlane.tools/LICENSE

Which gives a 404. It should instead point to a valid link, such as https://github.com/fastlane/fastlane/blob/master/LICENSE

(loving the docs site btw!)

**Comment by KrauseFx** [comment]
Nice catch, yeah that's correct. Do you want to submit a PR to https://github.com/fastlane/docs/blob/master/docs/index.md? 👍

**Comment by elitree** [comment]
Will do!

**Comment by KrauseFx** [comment]
Thanks 👍
