### ISSUE TITLE
[Discussion] if and where we want to use colourful boxes

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/docs#28]
Using a markdown parser extension (which we can define in `mkdocs.yml` we could have those nice colourful boxes in our docs: https://facelessuser.github.io/pymdown-extensions/

---

<img width="726" alt="screenshot 2016-08-25 18 21 57" src="https://cloud.githubusercontent.com/assets/869950/17991135/01032b82-6af1-11e6-911a-4642d982245d.png">

---

To render the box, only the following code is needed

```
!!! Caution "Reminder"
    Please read the [Usage Notes](usage_notes.md) for information on extension compatibility and general notes to be aware of when using these extensions.
```

I'd love to start using these boxes for things like:
- If fastlane is slow, try running `gem cleanup`
- If you have issues uploading a binary to iTunes Connect, check out the [FAQs](#)
- If you see a cryptic error message while building your app, try using the `use_legacy_build_api` option
- Make sure to use one GitHub repo per Developer Team, or specify a custom branch per team

Would love everyone's opinion about where we can use them and how much 👍

**Comment by kane6861** [comment]
I do consider all the concepts you've introduced to your post. They are really convincing and can definitely work. Nonetheless, the posts are too brief for newbies.
May you please extend them a bit from next time? Thank you for the post.
[KiK for iPad](http://www.kikforpcmessenger.com/)

**Comment by davix3210** [comment]
I prefer the summit. It really is excellent to find out an individual verbalize from your coronary heart and also quality with this crucial subject matter OF  may be effortlessly witnessed. Thanks again for your support, and remember: While one person can make a change, only together can we change the world.

Hope this help answer your query. 
Update us what works best for you. 
Regards
[Cinemabox app ](http://cinemaboxhd-apk.com/)
