### ISSUE TITLE
Implement centered header

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/docs#29]
## <img width="1096" alt="screenshot 2016-08-25 18 26 49" src="https://cloud.githubusercontent.com/assets/869950/17991226/88ae1ff6-6af1-11e6-9371-d108099ea2c6.png">

Basically what https://facelessuser.github.io/pymdown-extensions/ does. It's probably a markdown plugin, I'd love to start using it, as it looks much more polished than https://docs.fastlane.tools 👍

**Comment by KrauseFx** [comment]
The underlying code of the actual page is just
```
# Extensions {: .doctitle}
```

**Comment by joshdholtz** [comment]
@KrauseFx I _think_ current header is centered? 🤔 Is this issue taken care of?
