### ISSUE TITLE
Bamboo and Fastlane

### ISSUE THREAD

**Issue by LuffyCosta** [fastlane/docs#308]
Hello there i am trying to use fastlane in a bambo job at first it asked me to share the scheme in xcode. I did that after i ran the job again and it is saying  C**ode signing is required for product type 'Application' in SDK 'iOS 10.2'**

this is the code in the job:
cd /Users/bamboo/app
fastlane beta

Is there anything i have missed configuring the job, the job is just a simple console job

**Comment by KrauseFx** [comment]
Please submit the issue to the [fastlane main repo](https://github.com/fastlane/fastlane) 👍
