### ISSUE TITLE
Advanced.md change not propagated to https://docs.fastlane.tools/advanced/

### ISSUE THREAD

**Issue by GoodMirek** [fastlane/docs#314]
### Issue Description
Change https://github.com/fastlane/fastlane/commit/5c58300a1e46f1cfa9fea03dd21b617ebd695f0e to https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Advanced.md is not propagated to https://docs.fastlane.tools/advanced/
There is old content at https://docs.fastlane.tools/advanced/

**Comment by KrauseFx** [comment]
Currently it's synced manually unfortunately, do you want to submit a PR to bring those 2 up to date? We want to fix this long-term, but haven't had the time for it yet

**Comment by GoodMirek** [comment]
Thanks for response. Do you mean to propagate the change to
https://github.com/fastlane/docs/blob/master/docs/advanced.md or what should be the target file of PR?

**Comment by KrauseFx** [comment]
Mh, which one is ahead of the other one?

**Comment by GoodMirek** [comment]
https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Advanced.md is ahead of https://github.com/fastlane/docs/blob/master/docs/advanced.md

It seems https://docs.fastlane.tools/advanced/ is not generated from https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Advanced.md

I am just not sure whether the https://docs.fastlane.tools/advanced/ is generated from https://github.com/fastlane/docs/blob/master/docs/advanced.md or some another way, therefore I am not sure what to create Pull Request for.

**Comment by janpio** [comment]
Fastlane docs are now fully in this repo (core actions and external plugins excluded of course), so this should not be a problem any more.
