### ISSUE TITLE
Upload Symbols to Crashlytics

### ISSUE THREAD

**Issue by ansari-acacusgroup** [fastlane/docs#334]
I am using following lane to upload symbols to crashlytics:

`lane :refresh_dsyms do`
`download_dsyms                  # Download dSYM files from iTC`
`upload_symbols_to_crashlytics   # Upload them to Crashlytics`
`clean_build_artifacts           # Delete the local dSYM files`
`end`

Issue#1 - It always fetches all dSYM files and upload it, there is no way to keep track of already uploaded symbols.
Issue#2 - If there dSYM file is already dowloaded, it still downloads it again, and use the newly downloaded.

**Comment by KrauseFx** [comment]
Hey @ansari-acacusgroup, please submit an issue on the main repo, not the docs one 👍
