### ISSUE TITLE
Can't access the Available Plugins Page

### ISSUE THREAD

**Issue by swiftymarks** [fastlane/docs#363]
Issues submitted here should pertain to bugs/features of our [docs site](https://docs.fastlane.tools/).

If you're looking to submit an issue (bug/question/feature) about _fastlane_ itself, please do so in the [main repo](https://github.com/fastlane/fastlane/issues). 

It shows something like this
<img width="1680" alt="screen shot 2017-07-16 at 10 36 52 pm" src="https://user-images.githubusercontent.com/9997430/28248437-5f7ded4c-6a77-11e7-96b5-6f70785b68bd.png">

**Comment by KrauseFx** [comment]
What URL are you trying to access? https://docs.fastlane.tools/plugins/available-plugins/?

**Comment by swiftymarks** [comment]
Yes same link, I also tried it on Chrome just to be sure
<img width="728" alt="screen shot 2017-07-17 at 9 03 57 am" src="https://user-images.githubusercontent.com/9997430/28252884-f0afdd96-6ace-11e7-80c3-e064bbd2aa7f.png">

**Comment by KrauseFx** [comment]
From what country are you connecting from? Are you between a Firewall or VPN?

**Comment by swiftymarks** [comment]
I am from the Philippines. Not using the VPN or Firewall.

I can now access the link. Not sure what happened though. Even if I was in the office earlier the said link can't also be accessed there.
I'll close this issue for now.
