### ISSUE TITLE
Actions page isn't rendering HTML

### ISSUE THREAD

**Issue by getaaron** [fastlane/docs#379]
Looks like the Markdown isn't getting rendered on https://docs.fastlane.tools/actions/

Possibly related to https://github.com/fastlane/docs/commit/a7d30f54c4e370115bf07966c4893e00b8f3b4e1 (CC @ohayon @KrauseFx)

![image](https://user-images.githubusercontent.com/789577/28838289-c77e2cd4-76a4-11e7-8694-85d3b315bd3d.png)

**Comment by ohayon** [comment]
Thanks @getaaron !! We just submitted a fix for this and just waiting til CI finishes building it before merging and deploying the fix! 🚀  https://github.com/fastlane/fastlane/pull/9918

**Comment by ohayon** [comment]
This should be 💯  ! Thanks again for reporting it @getaaron ! 🚀

**Comment by KrauseFx** [comment]
❤️
