### ISSUE TITLE
Code signing instructions could be clearer under Xcode 8 section

### ISSUE THREAD

**Issue by jarshwah** [fastlane/docs#381]
I would like to suggest some improvements to the code signing documentation under the Xcode 8 section. This is my first time using Xcode and fastlane (inherited from another dev) so keep that in mind when I mention my pain points. They may not be pain points for the vast majority of users.

https://github.com/fastlane/docs/blame/master/docs/codesigning/xcode-project.md#L27

I spent quite a few hours trying to get code signing working again, because we had multiple targets that had to be built with separate certificates, and I was attempting to setup configuration via the `Build Settings` tab which is now **deprecated**.

I feel this line needs much more emphasis, including updating the associated screenshot:

> You can now specify which provisioning profile to use in the General tab after disabling Automatically manage signing.

The screenshot does not show **Automatically manage signing**, so it was easy for me to skip past. Honestly, I couldn't find the General/Signing page for quite awhile. And since I did find the Build Settings tab, I focused a lot of my attentions there.

So my suggestions would be:

1. Update the screenshot showing the General/Signing settings to show the **Automatically manage signing** unticked

2. Drop the **Alternatively** section that describes the **Build Settings** tab, which is deprecated from XCode 8.3 anyway, and doesn't seem to work in isolation.

I hope this feedback is useful.

**Comment by KrauseFx** [comment]
Sounds great, do you mind submitting a pull request for this change? :)

**Comment by jarshwah** [comment]
Sorry, I have other OSS obligations that will take priority before this and I'm not going to be a regular user as I'm just stepping in to help on our project briefly. I know drive by issues can be annoying so I'm sorry about that!

**Comment by janpio** [comment]
Fortunately Xcode 8 is not that relevant any more.
