### ISSUE TITLE
"Local actions" under "Create your own Plugins"

### ISSUE THREAD

**Issue by janpio** [fastlane/docs#394]
... should better be unter "Actions" somehow.

https://docs.fastlane.tools/plugins/create-plugin/#local-actions

Maybe change the list of Actions to "Available Actions" and add a "Create your own action" menu point equivalent to how it is done with plugins?

**Comment by janpio** [comment]
Ah, same for the next headline of that file:
https://docs.fastlane.tools/plugins/create-plugin/#submitting-the-action-to-the-fastlane-main-repo

**Comment by janpio** [comment]
Left side navigation seems to be defined here: https://github.com/fastlane/docs/blob/aeed433a6c275d9585723cc71e61c36190a56af6/mkdocs.yml

**Comment by janpio** [comment]
Some more thoughts:

* "Local actions" and "Submitting the action to the fastlane main repo should be moved to new page Actions => Local Action
* Current "Actions" functionality should be moved to Actions -> Available Actions
* "Plugins" text (with subheadlines) can be moved to top of "Available Plugins"
* "Create your own plugin" should get a note how plugins are listed under "Available Plugins" (rubygems.org search if I understood correctly)

**Comment by KrauseFx** [comment]
Yeah, those are some great ideas, thanks 👍  Do you want to submit a PR for this? cc @alexsinger

**Comment by janpio** [comment]
I will look into it.

How do you want to handle the fact that the content once was available on that document but is not any more after these changes? That is always a problem if you move stuff around and can't redirect it as it was only via anchors of sub-headlines :/

**Comment by janpio** [comment]
Started work on this in https://github.com/fastlane/docs/pull/655
