### ISSUE TITLE
"Using the Fabric app"

### ISSUE THREAD

**Issue by janpio** [fastlane/docs#398]
https://docs.fastlane.tools/ and https://github.com/fastlane/docs/blob/master/docs/index.md#using-the-fabric-app contain this:

> If you're not familiar with the terminal and prefer a graphical user interface, download the [Fabric app](https://get.fabric.io/) and use the built-in fastlane button.

I couldn't find this app and also not pulic documantation about it or a "fastlane button". Can someone please point me in the right direction?

**Comment by ohayon** [comment]
Hey @janpio, do you have a Fabric account? If so, you can use that to go in and download the Mac app which will help install _fastlane_: https://get.fabric.io/

**Comment by janpio** [comment]
Now I do, but is there no public site that shows a screenshot or anything that could give a not logged in user a bit more information?

**Comment by ohayon** [comment]
Thats good feedback. Thanks @janpio, we will make sure to pass that along 🚀

**Comment by janpio** [comment]
Ok, found it in the app now. Strangely had to add one of the "kits" first, then a "popup" for fastlane appeared that does some things. Great.
