### ISSUE TITLE
Improve search with DocSearch

### ISSUE THREAD

**Issue by spinach** [fastlane/docs#413]
The search on the docs page is not "as-you-type" and can improve. After having a quick chat with Felix at a conference, he seems to be very open to such idea.

At Algolia, we have [docsearch](https://github.com/algolia/docsearch) which can help you with that for free. We power the documentation of [Stripe](https://stripe.com/docs), [React](https://facebook.github.io/react/) and more. You can learn more about it [here](https://community.algolia.com/docsearch/).

**Comment by KrauseFx** [comment]
Awesome, just talked with the team, and they love the idea. Feel free to submit a PR to this repo (fastlane/docs) and we're happy to review & merge it 👍

**Comment by spinach** [comment]
That's great! We'll be in touch :)
