### ISSUE TITLE
Linkable anchor for individual plugins

### ISSUE THREAD

**Issue by janpio** [fastlane/docs#426]
https://docs.fastlane.tools/plugins/available-plugins/ could have linkable anchors for the individual plugins that could be used to link to a specific plugin (like would be [useful in search results for example](https://github.com/fastlane/docs/issues/425)).

**Comment by KrauseFx** [comment]
Yeah, sounds like a great idea 👍

**Comment by janpio** [comment]
This is not implemented:

![image](https://user-images.githubusercontent.com/183673/72687074-e9fb0a80-3afa-11ea-90a6-23982e986ef2.png)

https://docs.fastlane.tools/plugins/available-plugins/#versioning
