### ISSUE TITLE
Open external links in new tab by default

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/docs#43]
This should happen automatically. Also we have to make sure to properly set the tag to not give control over the tab to the external page

**Comment by danasilver** [comment]
The closest python-markdown extension that inserts `target="_blank"` is [markdown-newtab](https://github.com/Undeterminant/markdown-newtab), but it does it for all links. We could fork this and add a check for `'http' in elem.get('href')` [when](https://github.com/Undeterminant/markdown-newtab/blob/master/markdown_newtab/__init__.py#L23) it decides whether to add the attribute.

**Comment by danasilver** [comment]
I [forked](https://github.com/danasilver/markdown-newtab) markdown-newtab and added an `external_only` option as described above.

**Comment by mfurtak** [comment]
@i2amsam Dropped this in chat the other day. I don't know that it's relevant to a static site like this, but it seems worth mentioning: https://mathiasbynens.github.io/rel-noopener/ (talks about target=_blank vulnerabilities)

**Comment by KrauseFx** [comment]
@mfurtak 

>  Also we have to make sure to properly set the tag to not give control over the tab to the external page

Yeah, that's what I meant, but couldn't remember it was called `rel-noopener`, definitely important 👍

**Comment by danasilver** [comment]
That's a really interesting vulnerability I didn't know about. I think it's still valid for static sites. That makes more sense @KrauseFx; I figured you meant opening in the background like `Command + Click` does.

**Comment by janpio** [comment]
Is this still relevant? It's pretty common nowadays for links to just be opened in the same page/tab, and people using middle click or right-click -> new tab for this.
