### ISSUE TITLE
Action `plugin_scores` has strange description and wrong source code link

### ISSUE THREAD

**Issue by janpio** [fastlane/docs#430]
As I wanted to understand the plugin scoring, I found https://docs.fastlane.tools/actions/plugin_scores/ and two problems with it:

1. It has a strange description "[31mNo description provided[0m"
2. The "View source code" link to https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/plugin_scores.rb is wrong

**Comment by janpio** [comment]
Source for that generated page is here: https://github.com/fastlane/docs/blob/aeed433a6c275d9585723cc71e61c36190a56af6/docs/actions/plugin_scores.md

It is generated via fastlane/Fastfile here: https://github.com/fastlane/fastlane/blob/e4cd90157a559ca649d88ad8151881f16e8327b4/fastlane/Fastfile#L220-L224

MarkdownDocsGenerator is here: https://github.com/fastlane/fastlane/blob/76b098edf52f7a77c30cdcc6b1609825e398aa70/fastlane/lib/fastlane/documentation/markdown_docs_generator.rb
and ActionsList here: https://github.com/fastlane/fastlane/blob/76b098edf52f7a77c30cdcc6b1609825e398aa70/fastlane/lib/fastlane/documentation/actions_list.rb

And here I am lost.

Actual code of the action is here: https://github.com/fastlane/fastlane/blob/master/fastlane/actions/plugin_scores.rb
The actual scoring happens here: https://github.com/fastlane/fastlane/blob/master/fastlane/helper/plugin_scores_helper.rb

But this doesn't contain this strange description nor the source code link. Maybe the template for the docs?

**Comment by janpio** [comment]
No for the description, but yes for the "source code" link:
https://github.com/fastlane/fastlane/blob/76b098edf52f7a77c30cdcc6b1609825e398aa70/fastlane/lib/assets/ActionDetails.md.erb#L53
This doesn't work for that specific action :/

Description itself is from `action.description`. This comes from ActionsList here: https://github.com/fastlane/fastlane/blob/76b098edf52f7a77c30cdcc6b1609825e398aa70/fastlane/lib/fastlane/documentation/markdown_docs_generator.rb#L60
As this reads the files, my guess is that somewhere a missing description gets replaced with the error message that gets put on the page.

**Comment by janpio** [comment]
Comapre to random action that _has_ description confirms: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/clipboard.rb#L14-L16

No: Should `plugin_scores` be listed at all?
Probably not...

**Comment by KrauseFx** [comment]
Ahh, nah `plugin_scores` shouldn't be listed :)

**Comment by janpio** [comment]
Well, at least I learned a bit how the docs are built ;)

One way to "unlist" it would probably be to remove the category:
https://github.com/fastlane/fastlane/blob/master/fastlane/actions/plugin_scores.rb#L56-L58
as it will be skipped here then:
https://github.com/fastlane/fastlane/blob/76b098edf52f7a77c30cdcc6b1609825e398aa70/fastlane/lib/fastlane/documentation/markdown_docs_generator.rb#L26-L30
