### ISSUE TITLE
Document SharedValues and ENV variables created by actions

### ISSUE THREAD

**Issue by janpio** [fastlane/docs#468]
Is this already documented somewhere?
Can this documentation be generated?
What would have to change so this can be done?

**Comment by revolter** [comment]
The env variables are defined in the `options.rb` files (e.g. [gym's options](https://github.com/fastlane/fastlane/blob/master/gym/lib/gym/options.rb)). And I guess you have to edit [`ActionDetails.md.erb`](https://github.com/fastlane/fastlane/blob/bb53c93b57afcb263bc63bd54862d37c0811b2ee/fastlane/lib/assets/ActionDetails.md.erb#L40) to include `config_item.env_name`.

**Comment by janpio** [comment]
That can only be part of it. `gym` creates `SharedValues::IPA_OUTPUT_PATH` for example, `gradle` creates `SharedValues::GRADLE_APK_OUTPUT_PATH`.

**Comment by revolter** [comment]
I don't know about `SharedValues`, I was only referring to `env` variables.

**Comment by janpio** [comment]
A bit of investigation:

Some `SharedValues` seem to be "defined" here:
https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/gym.rb#L3-L6
But others are not listed there although set:
https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/gym.rb#L82
(Probably comes from somewhere else?)

`IPA_OUTPUT_PATH` is also written to an ENV variable:
https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/gym.rb#L77-L78
Same for `DSYM_OUTPUT_PATH`:
https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/gym.rb#L83

**Comment by revolter** [comment]
It's coming from https://github.com/fastlane/fastlane/blob/f08038b71e11d1338ca2222f3eaf9deff7c244c6/fastlane/lib/fastlane/actions/xcodebuild.rb#L5

**Comment by janpio** [comment]
> You don't need this information, as IPA_OUTPUT_PATH is defined in the SharedValues module, which can be extracted in the documentation.

If this is consistent across all actions and plugins... I assumed it may not be ;)

But I agree, exposing "SharedValues" would probably be a great first step.
Then maybe define some rules about how it should be used in actions and plugins so it is consistent.

**Comment by mollyIV** [comment]
👋 We created a ticket about documenting `SharedValues`: https://github.com/fastlane/fastlane/issues/14730

Maybe we can tackle ENV (environment variables for input parameters) in a separate ticket once we finish with the `SharedValues`? 🤔

**Comment by janpio** [comment]
Sounds like a plan. As ENV variables are not tracked anywhere, this might be a bit more effort though - maybe it makes sense to add something similar to `SharedValues` that also lists the ENV variables and also explains what they are used for.

**Comment by janpio** [comment]
@mollyIV, do you think we can/should close this issue as solved with what you implemented?

**Comment by mollyIV** [comment]
> Document SharedValues ...

The part about documenting `SharedValues` is already implemented ✔️ If you go to the _fastlane_ documentation, you can check what (if any) `SharedValues` are produced by an action, for instance [`build_ios_app` action](https://docs.fastlane.tools/actions/build_ios_app/#lane-variables).

> ... and ENV variables created by actions

We created separate tickets to tackle it:

* [Investigate usage of ENV vars in actions](https://github.com/fastlane/fastlane/issues/14915) ✔️ 
* [`ENV` variables used internally are backed-up by `SharedValues`](https://github.com/fastlane/fastlane/issues/15102) in-progress

So overall I think we can close this ticket  👍
