### ISSUE TITLE
More Structure for advanced.md

### ISSUE THREAD

**Issue by janpio** [fastlane/docs#469]
advanced.md is quite a collection of headlines right now. This could and should be structure a bit more to offer the user more guidance.

(Will probably only work if #455 is fixed somehow)

**Comment by janpio** [comment]
Current thoughts after reading through most of it:

- Writing lanes
- Appfile
- Writing actions

These could theoretically all go to their own file under /advanced, but also just be grouped by a superordinate headline.

**Comment by revolter** [comment]
I vote for separate files.

**Comment by janpio** [comment]
That would also enable us to start without waiting for #455 to get a proper solution by the way - which is a good thing.

Only reservation I have is that links to advanced.md with anchors to headlines can not really be redirected to their new location (unless you manually create the same headline there and a link to the new location) :/

**Comment by revolter** [comment]
Oh, that's kinda bad.

**Comment by janpio** [comment]
But pretty unavoidable if we want to change the docs site a lot... Will have to talk about it when the changes are ready one day.

**Comment by janpio** [comment]
Started work on this in #654
