### ISSUE TITLE
Enable linking to individual parameters on action pages

### ISSUE THREAD

**Issue by janpio** [fastlane/docs#488]
If you send someone a link to the docs of an action, quite often you want to point out a specific parameter. Would be great if each row had an anchor that could be used to link.

Open Question:
- Where to show this link? (Headlines show an icon on hover)

Futher ideas:
- Highlight linked parameter when opening and loading page

**Comment by KrauseFx** [comment]
Yeah great idea, the hover thing is very common 👍

**Comment by revolter** [comment]
StackOverflow [does it too](https://stackoverflow.com/a/11142257/865175).

**Comment by janpio** [comment]
> That solution looks like the simplest one, though replaced by an animation that resets the background color.

... which I never see as I only open stuff in background tabs ;)

(Useless trivia: I think Basecamp popularized that concept and wrote about it in a blogpost years ago)

**Comment by janpio** [comment]
Back to the original issue:

Problem right now is, that MkDocs doesn't have a way to set "empty" anchors on the page as far as I could find out. You can define strings as headlines, then the get an id if MkDocs is configured that way. But making the parameters headlines would be semantically incorrect :/

**Comment by revolter** [comment]
> ... which I never see as I only open stuff in background tabs ;)

Thought about that too, since I always have 100+ opened tabs and a lot of them are opened in batch. So we can leave it highlighted then.

Isn't there any pre-stuff block that allows you to "manually" fiddle with the generated HTML?

**Comment by janpio** [comment]
Note: Link/Anchor has probably to be added here: https://github.com/fastlane/fastlane/blob/9f0efb6117939e0c1501e226526605c29e3fb639/fastlane/lib/assets/ActionDetails.md.erb#L47

**Comment by revolter** [comment]
Shouldn't we close this when/if we actually implement it? Or at least have an opened issue in the fastlane repo for adding this functionality?

**Comment by janpio** [comment]
In a perfect world, yes.
In reality this is one of ~100 open issues no one is working on, so I am closing it.

Feel free to create a PR that adds this functionality though of course.

**Comment by revolter** [comment]
Would it be a good idea to label it to differentiate it from the implemented ones?

**Comment by janpio** [comment]
I created a milestone "Useful issues that were closed" where we can dump these. But to be honest, no one is really planning to work on these in the near future so this will not really change anything.

**Comment by revolter** [comment]
Great. And, I know, but I'm also hoping 😂
