### ISSUE TITLE
Incomplete and misleading example value for `backup_xcarchive`

### ISSUE THREAD

**Issue by Landschaft** [fastlane/docs#556]
On https://docs.fastlane.tools/actions/backup_xcarchive/ the example value for the `destination` parameter
    
      destination: "/somewhere/else/file.xcarchive", # Where the backup should be created

indicates that `destination` may be used to name the backup file but it really can only point to a directory that must already exist. I suggest to change the example value to `"/somewhere/else"`.

Moreover, the example should be completed with a `zip_filename` parameter.

**Comment by revolter** [comment]
Thank you for the catch 👍 I fixed it and will be live in the following days.
