### ISSUE TITLE
Replace pip with pipenv

### ISSUE THREAD

**Issue by revolter** [fastlane/docs#560]
I would want to know others opinion on replacing pip with pipenv.

I find it way better and easier to use. You don't have to create/modify either the `requirements` file either the `requirements-to-freeze` file, nor load it when installing the dependencies.

The only steps are:
- `pipenv --three` to create a virtual env
- `pipenv shell` to load the virtual env
- `pipenv install` to install the dependencies in the virtual env

And `pipenv install <dependency>` to add a new dependency (currently 3 steps).

Also, the current README doesn't mention virtual envs, so following the steps in it causes the packages to be installed globally.

I can do the migration and README/docs update myself.

**Comment by joshdholtz** [comment]
>Pipenv — the officially recommended Python packaging tool from Python.org, free (as in freedom).

Seems legit 😊 The current toolset "works" for me but I am not a Python pro so I don't really have any opinion for or against this.

**Comment by revolter** [comment]
It's actually just a wrapper over `virtualenv`.

**Comment by janpio** [comment]
Can this be closed @revolter?
