### ISSUE TITLE
is any changes for hybrid app build and deployment process?

### ISSUE THREAD

**Issue by shindekaps** [fastlane/docs#576]
Now days most of the apps developed using hybrid frameworks like Cordova. So is any chances for hybrid application.

**Comment by joshdholtz** [comment]
@shindekaps Heyyy 👋 Are you asking if...
1) Does fastlane support hybrid frameworks like Cordova?
or
2) Can documentation be added for building with hybrid frameworks?

**Comment by shindekaps** [comment]
Yes 
I am asking for both.

**Comment by janpio** [comment]
Well, I wrote "a bit" about using Fastlane with Ionic at https://ionic.zone/fastlane
As Ionic uses Cordova in the background, this all applies to normal Cordova apps as well.

**Comment by getaaron** [comment]
There’s also some support in `fastlane init` for setting up a React Native project

**Comment by joshdholtz** [comment]
I _do_ think we maybe could add a "Hybrid" section and has some references and best practices sections so its easier to find for people 🤔 Thoughts?

**Comment by janpio** [comment]
Duplicate of https://github.com/fastlane/docs/issues/626
