### ISSUE TITLE
Add a simple glossary

### ISSUE THREAD

**Issue by Cliabhach** [fastlane/docs#583]
It would be helpful to have a dedicated page just for clarifying common terminology. At a minimum, I propose explaining what the following mean:

* 'code signing'
* 'lane'
* 'provisioning'

It might also be nice to explain why the docs format the project name variously as fastlane, _fastlane_, and `fastlane`.

**Comment by janpio** [comment]
> It might also be nice to explain why the docs format the project name variously as fastlane, fastlane, and fastlane.

That is probably just an inconsistency. Feel free to point out specific locations.

For the glossary: We are open for PRs and would very much like that.

**Comment by Cliabhach** [comment]
Excellent, I'll get on those then.

**Comment by KrauseFx** [comment]
It should actually always be _fastlane_, except when shown as a command, then it's `fastlane beta` (for example)

**Comment by janpio** [comment]
(Here we have some brand guidelines ;) )
