### ISSUE TITLE
No documentation for submission_information

### ISSUE THREAD

**Issue by ConfusedVorlon** [fastlane/docs#584]
I'm getting an error on submission. I think it relates to my submission_information

I expected to find documentation on what would be correct (which keys are required) here

https://docs.fastlane.tools/actions/deliver/

Other than the note that submission_information exists - there are no details that I can find.

The question I want to answer is 'what keys do I need to submit an app which serves ads'

e.g. a correct version of this...

```
submission_information({
  add_id_info_uses_idfa: ENV['DLV_SERVES_ADS'],
  add_id_info_serves_ads: ENV['DLV_SERVES_ADS'],
  add_id_info_tracks_action: false,
  add_id_info_tracks_install: false,
  add_id_info_limits_tracking: true,
  export_compliance_uses_encryption: false,
  export_compliance_encryption_updated: false
})
```

**Comment by janpio** [comment]
This is actually documented, but hidden behind a `<details>`:

First go to https://docs.fastlane.tools/actions/upload_to_app_store/#more-options and open the collapsed information. Then go to https://docs.fastlane.tools/actions/upload_to_app_store/#submission_information. This also links to https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/app_submission.rb

Unfortunately the docs search doesn't find it either and it is also not directly linkable :/

**Comment by janpio** [comment]
Yep, that's why I labeled this as "bug". 

Any suggestion how to properly fix this?

**Comment by ConfusedVorlon** [comment]
sorry - I didn't catch that.

as to suggestions - how about just showing a typical complete set of options in
 
https://docs.fastlane.tools/actions/deliver/

it could be under the 'examples' section - or in the 'use in fastfile' section

**Comment by janpio** [comment]
I like the examples suggestion. Those come from https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/upload_to_app_store.rb#L49-L58, you could create a PR for that file.

**Comment by ConfusedVorlon** [comment]
no PRs on fastlane from me I'm afraid. 
I used to send them, but the process was so abominable I now limit myself to issues.

**Comment by janpio** [comment]
Uh, at least for documentation changes we are pretty quick to accept and merge PRs - but I don't know what you previous experience was.

Well, we can keep this issue around then and see if anyone picks it up. Thanks for the report then.
