### ISSUE TITLE
How to install fastlane  in windows?

### ISSUE THREAD

**Issue by maheshvammaravalli** [fastlane/docs#606]
Issues submitted here should consist of bugs/features of our [docs site](https://docs.fastlane.tools/).
If you're looking to submit an issue (bug/question/feature) about _fastlane_ itself, please do so in the [main repo](https://github.com/fastlane/fastlane/issues).

**Comment by joshdholtz** [comment]
@maheshvammaravalli fastlane is not officially supported on windows yet so closing this for now 😊

**Comment by avipars** [comment]
Has anything changed.. couldn't find official documentation on windows

**Comment by janpio** [comment]
Nope, big parts of the tooling fastlane is using is not available on Windows unfortunately.

**Comment by dimmduh** [comment]
Does it support linux or what? can not find how to install in docs or even requirements (

**Comment by MalteMagnussen** [comment]
Has anything changed yet? Is it available for Windows in any capacity?

**Comment by avipars** [comment]
Unofficially, it is
