### ISSUE TITLE
Different flavour push in different applicatin in playstore

### ISSUE THREAD

**Issue by taman123** [fastlane/docs#607]
Issues submitted here should consist of bugs/features of our [docs site](https://docs.fastlane.tools/).
If you're looking to submit an issue (bug/question/feature) about _fastlane_ itself, please do so in the [main repo](https://github.com/fastlane/fastlane/issues). 

Hello fastlane team . Glad to use fastlane to deploy projects. Really cool idea you have come up with. For single application its working perfectly. But i want to know is there any features to publish different application to playstore build on the basis of flavour of single project ? If not how can i handle such situation in the best way using fastlane?  Are you planning for such features?

**Comment by joshdholtz** [comment]
@taman123 Building different flavors of apps is already built natively into gradle 😊 So you can use the `gradle` action to build those specific flavors 💪
