### ISSUE TITLE
While running the fastlane beta "block (2 levels) in shift': [!] Illegal quoting in line 1. (CSV::MalformedCSVError)" 

### ISSUE THREAD

**Issue by nihp** [fastlane/docs#613]
Fastlane beta does not export the build to crashlytics. I got an error 

	/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/actions/register_devices.rb:38:in `run'
	/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/csv.rb:1346:in `read'
	/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/csv.rb:1289:in `open'
        /.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/csv.rb:1346:in `block in read'
	/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/csv.rb:1777:in `read'
	/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/csv.rb:1777:in `to_a'
	/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/csv.rb:1763:in `each'
	/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/csv.rb:1821:in `shift'
	/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/csv.rb:1821:in `loop'
	/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/csv.rb:1867:in `block in shift'
	/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/csv.rb:1867:in `each'
        /.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/csv.rb:1911:in `block (2 levels) in shift': [!] Illegal quoting in line 1. (CSV::MalformedCSVError)

**Comment by revolter** [comment]
Please post this to the _fastlane_ repo here: https://github.com/fastlane/fastlane/issues/new?template=BUG_REPORT.md with all the necessary information for easier debugging.

**Comment by nihp** [comment]
I have posted in fastlane repo. Thanks for your fast reply @revolter

**Comment by revolter** [comment]
No problem 😃
