### ISSUE TITLE
Broken actions search

### ISSUE THREAD

**Issue by revolter** [fastlane/docs#618]
The search is broken (at least for actions):

![image](https://user-images.githubusercontent.com/5748627/41095940-bb57fd6c-6a5b-11e8-9342-b1904944a7ba.png)

No menu from that list is going directly to the action's page.

**Comment by spinach** [comment]
@s-pace any clues what caused this?

**Comment by s-pace** [comment]
Happy to help here.

Could you tell us what is the expected behaviour @revolter ? It does redirect to the pages.

Thx

**Comment by s-pace** [comment]
Is it better this way? cc https://github.com/algolia/docsearch-configs/commit/5a076c820c3b23687f6f85271214715975aa7bdc

Cheers

**Comment by janpio** [comment]
Yes it is @s-pace:

![image](https://user-images.githubusercontent.com/183673/43511291-50f3c0da-9578-11e8-9c3c-59576ddefecd.png)

![image](https://user-images.githubusercontent.com/183673/43511319-64c6cd14-9578-11e8-99e5-0df082902d33.png)

Thanks.

Do you agree @revolter? Then we can probably close this.
