### ISSUE TITLE
switch to a lane defined in another file

### ISSUE THREAD

**Issue by ZZHHAANNGG** [fastlane/docs#623]
If I run fastlane getipa appstore:true, the error would be like this "Could not find action, lane or variable 'appstore_ipa'."  All these files are in the same folder. What do I miss?

```
import("appstore-Fastfile")
import("ent-Fastfile")
import("dev-Fastfile")

lane :getipa do |options|

  default_platform(:ios)

  if options[:development]
    development_ipa
  end

  if options[:enterprice]
    enterprise_ipa
  end

  if options[:appstore]
    appstore_ipa
  end
end
```

**_dev-Fastfile_**
```
platform :ios do
  desc "Build a development ipa"

  lane :development_ipa do |options|
  end

end
```

**_ent-Fastfile_**
```
platform :ios do
  desc "Build a enterprise ipa"

  lane :enterprise_ipa do |options|
  end

end
```

**_appstore-Fastfile_**
```
platform :ios do
  desc "Build a appstore ipa"

  lane :appstore_ipa do |options|
  end

end
```

**Comment by janpio** [comment]
I looked into this.

You can fix it by changing your `Fastfile` to:

```
import("appstore-Fastfile")
import("ent-Fastfile")
import("dev-Fastfile")

platform :ios do

	lane :getipa do |options|

	  if options[:development]
		development_ipa
	  end

	  if options[:enterprice]
		enterprise_ipa
	  end

	  if options[:appstore]
		appstore_ipa
	  end
	end

end
```

And using `fastlane ios getipa appstore:true` (or `bundle exec fastlane ios getipa appstore:true`) to execute the command.

Seems fastlane somehow gets tripped up by the different "platform" scopes. Can you please create an issue over at https://github.com/fastlane/fastlane/issues with includes this information, your files, and links to this issue? Thank you.
