### ISSUE TITLE
Bug: Broken Action Doc Links in docs/actions.md

### ISSUE THREAD

**Issue by philfi** [fastlane/docs#628]
Most (if not all) of the individual action doc links are broken because they are missing file extensions, i.e. `increment_build_number` should link to https://github.com/fastlane/docs/blob/master/docs/actions/increment_build_number.md but is currently pointed at https://github.com/fastlane/docs/blob/master/actions/increment_build_number

**Comment by revolter** [comment]
Where are you seeing the broken links?

**Comment by philfi** [comment]
sorry thought it was clear in the title, the page with the issue is https://github.com/fastlane/docs/blob/master/docs/actions.md

**Comment by philfi** [comment]
Also just noticed they seem to have incorrect paths to begin with, note that the correct version for the `increment_build_number` example I gave has the relative path `docs/actions` whereas the actual link in the `docs/actions.md` file is pointing at `actions/`. So two issues it appears, the relative paths are incorrect *and* missing extension
