### ISSUE TITLE
Proposal: move frameit to bottom of screenshots guide for iOS

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/docs#63]
Since frameit is mostly used for non-app store screenshots, the flow doesn't make a lot of sense for new users on https://docs.fastlane.tools/getting-started/ios/screenshots/. 

Instead I'd move the frameit information to the bottom and mention it after uploading the screenshots to the app store

**Comment by mfurtak** [comment]
OK with me 👍

**Comment by KrauseFx** [comment]
Done 👍
