### ISSUE TITLE
Separate actions and tools?

### ISSUE THREAD

**Issue by janpio** [fastlane/docs#652]
Currently e.g. both `supply` and `upload_to_play_store` are listed as "Actions" and have very similar documentation:

https://docs.fastlane.tools/actions/supply/
https://docs.fastlane.tools/actions/upload_to_play_store/

But in reality `supply` is a command line tool that offers `fastlane supply`, `fastlane supply init` and similar commands, while `upload_to_play_store` is an action that can be used to do part of the CLI functionality via lanes (and is historically also available as the action alias `supply`).

This applies to other tools and actions as well, of course.

In my opinion the fastlane docs would benefit from separating these two different concepts more clearly:

- Add new "Tools" menu option on the left
- Separate tool and action documentation, move `supply`, `gym` etc. to Tools
- Tools is a new overview page list similar to the Actions list, that explains what it is all about and lists the tools in a list or table

**Comment by janpio** [comment]
Having the action docs removed from the tool page, it would enable us to add some interesting information:

- Commands list
- Parameters list (probably quite identical to that of action?)
- Configuration file

**Comment by janpio** [comment]
With extracted tool documentation, fastlane could get rid of the special handling of some action documentation where an additional markdown file is attached before the actual action docs. These markdown files would then be used for the new tools docs.

**Comment by janpio** [comment]
Notes: `tools.md`, `mkdocs.yml` and `tools/...` would have to be generated for the tools similar to how currently for actions.

Relevant code:
https://github.com/fastlane/fastlane/blob/e3afc4105988d3aaf4b2bef746f4101eeb441af9/fastlane/lib/fastlane/documentation/markdown_docs_generator.rb
https://github.com/fastlane/fastlane/blob/665a23e6351702bbd6980fe1f7ec75a6f1f7bfa6/fastlane/Fastfile#L340

**Comment by janpio** [comment]
The connected PR has most of this implemented for demonstration:

https://deploy-preview-657--fastlane-docs-preview.netlify.com/tools/
https://deploy-preview-657--fastlane-docs-preview.netlify.com/tools/gym/
https://deploy-preview-657--fastlane-docs-preview.netlify.com/actions/gym/
https://deploy-preview-657--fastlane-docs-preview.netlify.com/actions/build_ios_app/

**Comment by taquitos** [comment]
Maybe where we talk about `alias` we should make it known that people aren't expected to understand aliases. 
Like, `Advanced fastlane users:  ___ is an alias for ___`

**Comment by janpio** [comment]
I was convinced via Slack that this is not the way to go - tools are just actions.
