### ISSUE TITLE
Code samples should show Fastfile samples

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/docs#7]
To make `fastlane` *the* tool for deploying, let's get more people to start using `fastlane` itself too:

Let's use the following for all code samples:

```ruby
snapshot(scheme: "something")
sigh(user: "user@something.com")
```

and also mention that you can call each tool from the command line using

```
fastlane snapshot --scheme "something"
fastlane sigh -u user@something.com
```

(note that we prefix all calls with fastlane)

Install instructions should also always mention `[sudo] gem install fastlane --verbose`, and not an individual tool (with the exception of `spaceship`)

**Comment by mfurtak** [comment]
Sounds good to me.

**Comment by KrauseFx** [comment]
Proposal approved 👍
