### ISSUE TITLE
Links to fastlane.tools that redirect to docs

### ISSUE THREAD

**Issue by janpio** [fastlane/docs#701]
https://fastlane.tools/cert
linked from:
https://docs.fastlane.tools/codesigning/getting-started/

https://fastlane.tools/match
linked from:
https://docs.fastlane.tools/codesigning/xcode-project/
https://docs.fastlane.tools/codesigning/getting-started/
https://docs.fastlane.tools/best-practices/continuous-integration/
https://docs.fastlane.tools/codesigning/troubleshooting/
https://docs.fastlane.tools/actions/build_ios_app/
https://docs.fastlane.tools/actions/build_app/
https://docs.fastlane.tools/actions/gym/

https://fastlane.tools/sigh
linked from:
https://docs.fastlane.tools/codesigning/getting-started/
https://docs.fastlane.tools/codesigning/troubleshooting/

https://fastlane.tools/supply
linked from:
https://docs.fastlane.tools/actions/screengrab/
https://docs.fastlane.tools/actions/capture_android_screenshots/

Is that reroute intentional @KrauseFx ?

**Comment by janpio** [comment]
Are those `fastlane.tools/[tool_name]` URls used anywhere else?

**Comment by KrauseFx** [comment]
@janpio It's used in various Stackoverflow replies and other external websites. Any reason we wouldn't want to keep them around?

**Comment by janpio** [comment]
Nah, but if they are only there for legacy reasons, we could replace the links in the docs itself to the direct action links so they don't spread any further (right click -> copy link -> post somewhere).
