### ISSUE TITLE
[bug/question/feature] secure JSON file

### ISSUE THREAD

**Issue by kirshanluhana** [fastlane/docs#702]
Currently in Fastlane we are providing JSON file as 

` json_key:                   'path/my.json',`

to secure JSON key on CI server, we want to provide it via password parameter 
and access this via some script like this

data.sh
```

#!/bin/sh
$JSONData
```
and assign this instead of JSON file
` json_key:                   'path/data.sh',`

Or any idea to provide securily JSON file, which should not save on filesystem

**Comment by janpio** [comment]
What is the difference between having it in a `.json` and in a `.sh` file?

**Comment by kirshanluhana** [comment]
thanks
JSON file has the key information, which could be hacked if on filesystem. 
The sh file will receive information from an environmental variable, which will be in memory and secure. 
or any way to provide echo $data instead of file ??
I see this helpful for many.

**Comment by kirshanluhana** [comment]
Just in issue section I read very first question which I am trying to address

https://github.com/fastlane/fastlane/issues/13185

**Comment by janpio** [comment]
This depends on where you are using `json_key`. If it is with `supply`, then there is also a parameter `json_key_data` that can consume a environment variable: https://docs.fastlane.tools/actions/supply/#parameters

**Comment by kirshanluhana** [comment]
Thank you very much for hint
