### ISSUE TITLE
Broken react-native video link 

### ISSUE THREAD

**Issue by jmatsushita** [fastlane/docs#719]
On this page https://docs.fastlane.tools/getting-started/cross-platform/react-native/ the `Conference talk "Automate your React Native world with fastlane"` link points to an unavailable video:
```
Video unavailable
This video is no longer available because the uploader has closed their YouTube account.
```

**Comment by janpio** [comment]
Was probably this one:
https://www.youtube.com/watch?v=1K5OLv3moFg
https://speakerdeck.com/philtrep/automate-your-react-native-world-with-fastlane
Correct @KrauseFx ?

**Comment by KrauseFx** [comment]
Yes, nice catch, thanks

**Comment by janpio** [comment]
Video link works now
