### ISSUE TITLE
Documentation: Android setup documentation should not require Xcode

### ISSUE THREAD

**Issue by philjoseph** [fastlane/docs#724]
Reading the documentation I see mention to Xcode. This is confusing.

![image](https://user-images.githubusercontent.com/4303547/45921097-71a91880-beb7-11e8-91f2-3082045d6be0.png)

I am still searching the way to init fastlane for an Android only project

**Comment by ZhukovAlexander** [comment]
This could be reeealy confusing for newcomers with almost 0 experience.

**Comment by lyndsey-ferguson** [comment]
Do they not need this first step to install Ruby and other tools too?

**Comment by Joel-wilks1588** [comment]
Hello,
thanks for sharing your query.
you not need to follow this step so just skip that.

**Comment by rogerluan** [comment]
This has been updated and is no longer an issue.
