### ISSUE TITLE
Matchfile example outdated? 

### ISSUE THREAD

**Issue by yzhong52** [fastlane/docs#727]
I think the example `fastlane` `match` content is out dated? 

```
git_url("https://github.com/fastlane/certificates")

app_identifier("tools.fastlane.app")
username("user@fastlane.tools")
```

When running `fastlane match init` with the latest version, this is the following output

```
git_url "https://github.com/fastlane/certificates"

type "development"

app_identifier ["tools.fastlane.app", "tools.fastlane.app2"]
username "user@fastlane.tools" # Your Apple Developer Portal username
```

**Comment by KrauseFx** [comment]
Whoah, `fastlane match init` creates an array of app identifiers? Or are they commented out?

**Comment by yzhong52** [comment]
Hey, @KrauseFx, they were commented out. This is the original output:

```
git_url "https://github.com/fastlane/certificates"

type "development" # The default type, can be: appstore, adhoc, enterprise or development

# app_identifier ["tools.fastlane.app", "tools.fastlane.app2"]
# username "user@fastlane.tools" # Your Apple Developer Portal username

# For all available options run `fastlane match --help`
# Remove the # in the beginning of the line to enable the other options
```

I think the current doc maybe out of date? My guess is that there is a previous version where the syntx of the Matchfile is a bit different with paranthsis like function calls?

**Comment by yzhong52** [comment]
Actually, it may be a styling issue and both of them is correct? I can validate tomorrow morning also.

**Comment by yzhong52** [comment]
@KrauseFx So they are the indeed same, just using two different styles. I am closing this. Sorry for the noise. My only recommendation would be to use the same style in both the init auto-generated code and the doc. But it is not a big deal.
