### ISSUE TITLE
Outdated parts

### ISSUE THREAD

**Issue by janpio** [fastlane/docs#742]
Parts of the documentation are outdated and refer to names and commands that do not work any more:

- https://docs.fastlane.tools/actions/pem/#features, gif of `pem` still uses just `pem` instead of `fastlane pem`.

**Comment by KrauseFx** [comment]
To be honest, it's probably not worth creating new screen videos for those, it takes quite some time creating high quality ones, including converting and uploading them

**Comment by KrauseFx** [comment]
Yeah, they're still good I believe. The output has also changed, but it still explains what the tool does I believe
