### ISSUE TITLE
<details> in documentation pages hides vital information, can not be searched with Ctrl+F

### ISSUE THREAD

**Issue by janpio** [fastlane/docs#747]
https://github.com/fastlane/docs/issues/584
https://github.com/fastlane/fastlane/issues/13730

**Comment by KrauseFx** [comment]
Yah good point, how can we fix it?

**Comment by janpio** [comment]
Get rid of the `<details>` tag, but then we will have to "refactor" the docs pages to make them more concise or split them into subpages I guess :/ Not very optimal.
