### ISSUE TITLE
iOS setup does not mention 2-factor authentication

### ISSUE THREAD

**Issue by ehmjaysee** [fastlane/docs#813]
Two-factor authentication is already explained in the Fastlane documentation, however there is no mention about this on the iOS setup page for new users. Apple now mandates TFA.

**Comment by janpio** [comment]
Good observation. Certainly makes sense to point people in the right direction in the moment when they need it.

There are currently several open issues and PRs (all from me...) about improving the documentation on authentication in general, I will just add this to my list.
