### ISSUE TITLE
The parameter of auto_release_date cannot be used with automatic_release, Not documented

### ISSUE THREAD

**Issue by ataranlen** [fastlane/docs#817]
In all of the references to `auto_release_date` there are no references to the fact that it cannot be used along with `automatic_release`. The only reference I could find to this restriction is in the deliver options.rb file.

It would be helpful to call this out in the documentation.

https://github.com/fastlane/fastlane/blob/049fe3dd417955c28c4365640c89c0db565ac663/deliver/lib/deliver/options.rb#L162

**Comment by janpio** [comment]
Yeah, you could probably add it to the `description` string of that option. Open a PR and we can merge it.
