### ISSUE TITLE
deliver: Available language lists do not match

### ISSUE THREAD

**Issue by rajivshah3** [fastlane/docs#828]
`deliver`'s [list of available language codes](https://docs.fastlane.tools/actions/deliver/#available-language-codes) seems to be generated by a script. However, [this list](https://docs.fastlane.tools/actions/deliver/#available-languages) on the same page looks out of date. I'm happy to fix this, but I didn't know whether it's best to just remove the outdated list since it's essentially a duplicate of another list on the same page.

**Comment by janpio** [comment]
But: Be aware that the docs of deliver are generated. This is the source: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/docs/upload_to_app_store.md.erb#L594
