### ISSUE TITLE
Jenkins Environment variable in Deliverfile

### ISSUE THREAD

**Issue by Abhishekqwerty** [fastlane/docs#833]
How can we use Jenkins Environment variable like $WORKSPACE in path of ipa file used in Deliverfile
Eg: ipa("$WORKSPACE/App.ipa")

**Comment by janpio** [comment]
A `Deliverfile` is also normal ruby, so `ENV['WORKSPACE']` should probably work:

```
ipa(ENV['WORKSPACE'] + "/App.ipa")
```

https://github.com/fastlane/fastlane/issues is the better place for such actions about fastlane, and not about the docs themselves.
