### ISSUE TITLE
Tip: "Available session is not valid any more, Continuing with normal login." ？

### ISSUE THREAD

**Issue by sigelion** [fastlane/docs#836]
### 4、Thank you.

**Comment by getaaron** [comment]
Hi 👋 

You can read more comments about the implementation in the comments

https://github.com/fastlane/fastlane/blob/db8e09bdb0b3462c57c4250224fbdb731a8c3992/spaceship/lib/spaceship/client.rb#L400-L513

This is the documentation repo, please open an issue in the regular fastlane repo
