### ISSUE TITLE
Screenshot documentation has old device names

### ISSUE THREAD

**Issue by fulldecent** [fastlane/docs#845]
The documentation at 

https://github.com/fastlane/docs/blob/706d98f340590aef4f13c40bf93cae7bd1bc35da/docs/getting-started/ios/screenshots.md

Cites a list of devices which is not the current list of devices which developers will be wanting to make screenshots with:

```
# A list of devices you want to take the screenshots from
# devices([
#   "iPhone 6",
#   "iPhone 6 Plus",
#   "iPhone 5",
#   "iPhone 4s",
#   "iPad Retina",
#   "iPad Pro"
# ])
```

Please update this to the current list. Also please add a link to documentation of all supported device names.

**Comment by janpio** [comment]
We will be happy to merge a Pull Request of an updated list of devices. Can you create one?
