### ISSUE TITLE
Is scan or run_tests the preferred command?

### ISSUE THREAD

**Issue by macblazer** [fastlane/docs#889]
This page https://docs.fastlane.tools/actions/#testing specifically says the `scan` description is "Alias for the `run_tests` action".  However, it also has the `run_tests` description as "Easily run tests of your iOS app (via `scan`)".  This is a circular reference, and it is confusing.

The details page for scan at https://docs.fastlane.tools/actions/scan/ has a first line of "Alias for the `run_tests` action" but then it has a very detailed description with screenshots and lots of words all about `fastlane scan`.  However, most of the examples call `run_tests` instead of `scan`.  Again, this is a confusing mix of `scan` and `run_tests`.

The details page for run_tests at https://docs.fastlane.tools/actions/run_tests/ looks pretty much like a full copy of the `scan` docs page except for the first line which is "Easily run tests of your iOS app (via scan)".  Again, a confusing mix of `scan` and `run_tests`.

Which one of these commands is the preferred usage?  That preferred usage page should be updated as much as possible to only refer to the preferred usage.  The other details page should be reduced to a simple link to the preferred usage page.

I'm happy to take on the work of updating these few pages to better clarify what the intended/preferred public command is for running the tests.

**Comment by janpio** [comment]
There is no really preferred version. We have to do a much bigger cleanup, before we can fully switch from `scan` (which is the older action) to `run_tests` (which is the newer one). That span all actions and tools and is a massive undertaking, that we are currently not keen on tackling.
