### ISSUE TITLE
2FA Apple auth info in Fastlane docs is incorrect

### ISSUE THREAD

**Issue by badsprad** [fastlane/docs#913]
The "Separate Apple ID for CI" info located here is incorrect:
https://docs.fastlane.tools/best-practices/continuous-integration/

The only way that a separate Apple ID will work is if you have a developer account that IS NOT and individual status / i.e. it is a business organisation.

This is the only way that you can get the other Apple ID account to modify access to Certificates, Identifiers & Profiles.

More info here:
https://stackoverflow.com/questions/36935087/cant-access-certificates-identifiers-profiles-within-developer-apple-com/56581774

**Comment by janpio** [comment]
What exactly is wrong there? Is it missing some information?
Which answer are you linking to on the Stackoverflow question?

**Comment by badsprad** [comment]
The key issue is using a CI service (I use Github Actions) and Fastlane certificate automation, as you need to have a "separate" Apple ID that:
1) belongs to an "Organisation" (and is not Individual type)
2) does not have 2FA 
3) has a role of "App Manager" / is not "Account Holder"

So the current Fastlane docs assume that your Apple Developer account is an "organisation" type, and if you wish to change from an Individual to an Organisation account, then you'll need to input your business credentials etc.

For example, my Apple Developer account is an "Individual" type:

![image](https://user-images.githubusercontent.com/4809356/76710688-b1278c80-675d-11ea-9d0b-b70fa59d4643.png)


![image](https://user-images.githubusercontent.com/4809356/76710693-bd134e80-675d-11ea-9b95-fb1a82c8d9de.png)


This part of the Fastlane docs is incorrect, as it skips the part about the "Organisation" account type:
https://docs.fastlane.tools/best-practices/continuous-integration/

![image](https://user-images.githubusercontent.com/4809356/76710787-5cd0dc80-675e-11ea-96de-606a27a49ab5.png)

**2 verifying sources are:**

1) When you try to access this link (in order to manage/view certificates) in your "separate" AppleID account, you get this error:

https://developer.apple.com/account/resources/certificates/list

![image](https://user-images.githubusercontent.com/4809356/76710830-c05b0a00-675e-11ea-84bb-0fba1a7eaec3.png)

2) Stackoverflow advice:

https://stackoverflow.com/questions/36935087/cant-access-certificates-identifiers-profiles-within-developer-apple-com/56581774

![image](https://user-images.githubusercontent.com/4809356/76710872-10d26780-675f-11ea-9c0e-27a543a99474.png)

**Comment by janpio** [comment]
So we should add that it has to be an org account?

**Comment by badsprad** [comment]
Yes please, and also the fact that if you are not able to obtain an "Organisation" account type, then you are unable to use any Fastlane automation in a CI workflow (correct me if I'm wrong here...)
