### ISSUE TITLE
Doc recommends Apple ID without 2FA enabled but doesn't say how

### ISSUE THREAD

**Issue by fdstevex** [fastlane/docs#938]
Referring to:
https://docs.fastlane.tools/best-practices/continuous-integration/

"The easiest way to get fastlane running on a CI system is to create a separate Apple ID that doesn't have 2-factor authentication enabled"

It may be the "easiest" way but there's no description of how to do it, and as far as I can tell it's currently impossible?  If there is a way, I haven't discovered it.

**Comment by chris-griffin** [comment]
I spent a decent amount of time on the phone with Apple Support (Developer and Apple ID) over the last week, and they came to the conclusion that it is no longer possible as of a very recent date.

**Comment by fdstevex** [comment]
I'm trying to determine if it's possible through the Apple Business Manager.  That's the only avenue I have left to try.  Anyone know if you can create a Managed Apple ID through that without 2FA and use it with Fastlane for CI?

**Comment by fdstevex** [comment]
We've set up our company with Apple Business Manager, and I can confirm it's not possible to create an Apple ID without 2FA through that route either.
