### ISSUE TITLE
download_dsyms doesn't check for 3 level version number.

### ISSUE THREAD

**Issue by userException** [fastlane/docs#976]
lane :upload_symbols do
    download_dsyms(
      version: 'latest',
      wait_for_dsym_processing: 'true'
      )
end

This lane works when the version number for my app is 1.0, 2.0, X.0.

Let's say I uploaded 1.0.1 version to testflight, then it still checks for latest version for 1.0. Here is the log:

**After uploading to testflight:**

Successfully finished processing the build 1.0.1 - 6 for IOS

**But on upload_symbols step:**

out: [02:52:41]: Login successful
35	out: [02:52:44]: Looking for latest version...
36	out: +------------------+--------------------+
37	out: |             Lane Context              |
38	out: +------------------+--------------------+
39	out: | DEFAULT_PLATFORM | ios                |
40	
41	out: | PLATFORM_NAME    | ios                |
42	out: | LANE_NAME        | ios upload_symbols |
43	out: +------------------+--------------------+
44	out: [02:52:44]: Could not find latest build for version 1.0
45	out:

**Comment by revolter** [comment]
Please submit this issue (if it's still valid) to the https://github.com/fastlane/fastlane repo instead. Thank you!
