### ISSUE TITLE
Search field missing on mobile device

### ISSUE THREAD

**Issue by nysander** [fastlane/docs#979]
When I browse Fastlane docs page on Safari mobile (iPhone 8+) there is only sandwich menu but I cannot search for content like on desktop Safari.

![IMG_1DFC05FAC913-1](https://user-images.githubusercontent.com/753327/93609253-e5f5f400-f9cb-11ea-8025-d6e359314ffa.jpeg)

**Comment by revolter** [comment]
It shows up for me, now. Could you please test this again? 😃

**Comment by rogerluan** [comment]
For me as well 👍 fastlane docs have gone through a large revamp/upgrade since the creation of this ticket, this probably fixed the underlying issue observed 😊 Let us know if that's not the case @nysander ! 🙏 Thanks for reporting this issue! Closing it for now 👍
